version: '3'

vars:
  GO_VERSION: '1.26.4'
  GOLANGCI_LINT_VERSION: 'v2.13.2'
  GCI_VERSION: 'v0.14.0'
  GOFUMPT_VERSION: 'v0.12.0'
  GOLINES_VERSION: 'v0.15.0'
  GOLANG_MIGRATE_VERSION: 'v4.20.1'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT_PATH: '{{.BIN_DIR}}/golangci-lint'
  GCI_PATH: '{{.BIN_DIR}}/gci'
  GOFUMPT_PATH: '{{.BIN_DIR}}/gofumpt'
  GOLINES_PATH: '{{.BIN_DIR}}/golines'
  GOLANG_MIGRATE_PATH: '{{.BIN_DIR}}/migrate'

  POSTGRES_HOST: 'localhost'
  POSTGRES_PORT: '5432'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgres'
  POSTGRES_DB: 'shortlink'
  POSTGRES_SSL_MODE: 'disable'

  MIGRATION_DSN: 'postgres://{{.POSTGRES_USER}}:{{.POSTGRES_PASSWORD}}@{{.POSTGRES_HOST}}:{{.POSTGRES_PORT}}/{{.POSTGRES_DB}}?sslmode={{.POSTGRES_SSL_MODE}}'
  MIGRATION_DIR: '{{.ROOT_DIR}}/migrations'

tasks:
  bin:
    desc: Create bin directory
    cmds:
      - mkdir -p {{.BIN_DIR}}
    status:
      - test -d {{.BIN_DIR}}
  install:
    desc: Install tools
    deps: [bin]
    env:
      GOBIN: '{{.BIN_DIR}}'
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
      - go install github.com/daixiang0/gci@{{.GCI_VERSION}}
      - go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
      - go install github.com/golangci/golines@{{.GOLINES_VERSION}}
      - go install -tags "postgres" github.com/golang-migrate/migrate/v4/cmd/migrate@{{.GOLANG_MIGRATE_VERSION}}
    status:
      - test -x {{.GOLANGCI_LINT_PATH}}
      - test -x {{.GCI_PATH}}
      - test -x {{.GOFUMPT_PATH}}
      - test -x {{.GOLINES_PATH}}
      - test -x {{.GOLANG_MIGRATE_PATH}}
  lint:
    desc: Run golangci-lint
    deps: [install]
    cmds:
      - '{{.GOLANGCI_LINT_PATH}} run ./... --config={{.ROOT_DIR}}/.golangci.yml'
  format:
    desc: Run formatters
    deps: [install]
    cmds:
      - find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GOFUMPT_PATH}} -extra -w {} +
      - find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GCI_PATH}} write -s standard -s default -s "prefix(github.com/RomanDeveloperGit/shortlink-link-api/)" {} +
      - find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GOLINES_PATH}} -w {} +
  migrate:create:
    desc: Run create migration
    deps: [install]
    cmds:
      - '{{.GOLANG_MIGRATE_PATH}} -database {{.MIGRATION_DSN}} create -ext sql -dir {{.MIGRATION_DIR}} {{.CLI_ARGS}}'
  migrate:up:
    desc: Run up migration
    deps: [install]
    cmds:
      - '{{.GOLANG_MIGRATE_PATH}} -database {{.MIGRATION_DSN}} -path={{.MIGRATION_DIR}} up {{.CLI_ARGS}}'
  migrate:force:
    desc: Run force migration
    deps: [install]
    cmds:
      - '{{.GOLANG_MIGRATE_PATH}} -database {{.MIGRATION_DSN}} -path={{.MIGRATION_DIR}} force {{.CLI_ARGS}}'
  migrate:down:
    desc: Run down migration
    deps: [install]
    cmds:
      - '{{.GOLANG_MIGRATE_PATH}} -database {{.MIGRATION_DSN}} -path={{.MIGRATION_DIR}} down {{.CLI_ARGS}}'
  migrate:version:
    desc: Run version migration
    deps: [install]
    cmds:
      - '{{.GOLANG_MIGRATE_PATH}} -database {{.MIGRATION_DSN}} -path={{.MIGRATION_DIR}} version'
  run:
    desc: Run server
    env:
      ENV: 'local'
      SERVICE_NAME: 'shortlink-link-api'
      SERVICE_VERSION: '0.0.0'
      SHORT_LINK_LENGTH: '7'
      ATTEMPTS_GENERATE_SHORT_LINK_LIMIT: '5'
      GRACEFUL_SHUTDOWN_PER_RESOURCE_TIMEOUT: '15s'
      HTTP_HOST: '0.0.0.0'
      HTTP_PORT: '8080'
      HTTP_IDLE_TIMEOUT: '10s'
      HTTP_READ_TIMEOUT: '10s'
      HTTP_WRITE_TIMEOUT: '10s'
      POSTGRES_HOST: '{{.POSTGRES_HOST}}'
      POSTGRES_PORT: '{{.POSTGRES_PORT}}'
      POSTGRES_USER: '{{.POSTGRES_USER}}'
      POSTGRES_PASSWORD: '{{.POSTGRES_PASSWORD}}'
      POSTGRES_DB: '{{.POSTGRES_DB}}'
      POSTGRES_SSL_MODE: '{{.POSTGRES_SSL_MODE}}'
      POSTGRES_MAX_IDLE_CONNS: '10'
      POSTGRES_MAX_OPEN_CONNS: '100'
      POSTGRES_CONN_MAX_LIFETIME: '5m'
      POSTGRES_PING_TIMEOUT: '5s'
    cmds:
      - go run ./cmd/api
